spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password:
   
    h2:
        console:
            enabled: true